### PR TITLE
Use asynchronous Mutex for response sinks

### PR DESCRIPTION
**Pull request by llebout**
`std::sync::Mutex` is blocking. Keep in mind to never use in asynchronous code!

### CODE REVIEW

**Comment by pietgeursen** [comment]
Hey @leo-lb, have you signed the [contributor agreement](https://github.com/sunrise-choir/meta/blob/master/processes/cla.md)?

Keen to get this merged if so.

cc @ahdinosaur

**Comment by llebout** [comment]
@pietgeursen 
Hey! No I haven't but I realized I probably do not want to. I have no interest in giving up my copyright on AGPL code. I have no interest on allowing code to be re-licensed under anything else than AGPL.

**Comment by pietgeursen** [comment]
Fair enough @leo-lb. 

Is it ok if I close your PR's then?

Thanks for taking the time all the same. It's a shame we can't use your work. :crying_cat_face:

**Comment by llebout** [comment]
@pietgeursen

I think you'll have to do that yes, unless anybody changes their mind.
I find it a bit unfair to require people to give up their copyright in any case. I don't think it's a good practice in a community project. If a license change must happen then you'll have to deal with asking everyone if they agree to relicense, that's inevitable. If people don't, then you'll have to rewrite their code. I don't think there's any fair way around this. You could set up a legal entity with every developers as governing members and then they can handle license changes differently? (Super)-Majority votings? Purchase copyright from selected developers if they don't want to change the license..?

**Comment by pietgeursen** [comment]
> unless anybody changes their mind.

I don't think that's likely, it's an important part of sunrise choir, as far as I understand. 

FYI, the requirement comes from @ahdinosaur, he's the one who has personally funded sunrise choir. I completely trust his motivations, he's my friend, I know him personally. But I get that if you don't know us it probably seems... weird.

All the best, and thanks again.

**Pull request closed without merging**
